# Schema for the configuration files of the User bundle module.

user_bundle.settings:
  type: config_object
  label: 'User bundle settings'
  mapping:
    registration_user_type:
      type: string
      label: 'Visitor registration account type'

user_bundle.user_type.*:
  type: config_entity
  label: 'Account type'
  mapping:
    id:
      type: string
      label: 'Machine-readable name'
    label:
      type: label
      label: 'Name'
    description:
      type: text
      label: 'Description'
