field.field_settings.entity_reference_quantity:
  type: field.field_settings.entity_reference
  label: 'Entity reference override'
  mapping:
    qty_label:
      type: string

field.storage_settings.entity_reference_quantity:
  type: field.storage_settings.entity_reference
  label: 'Entity reference quantity'

field.formatter.settings.entity_reference_quantity_label:
  type: field.formatter.settings.entity_reference_label
  mapping:
    location:
      label: 'Show quantity as'
      type: string
    template:
      label: 'Output template'
      type: string
