# Schema for the Inline Entity Revision Reference module display settings.

field.widget.settings.inline_entity_revision_form_simple:
  type: mapping
  label: 'Inline entity reference display format settings'
  mapping:
    form_mode:
      type: string
      label: "Form mode"
    override_labels:
      type: boolean
      label: "Override labels"
    label_singular:
      type: string
      label: "Label (singular)"
    label_plural:
      type: string
      label: "Label (plural)"
    allow_new:
      type: boolean
      label: "Allow new"
    allow_existing:
      type: boolean
      label: "Allow existing"
    match_operator:
      type: string
      label: "Match operator"
    collapsible:
      type: boolean
      label: "Collapsible"
    collapsed:
      type: boolean
      label: "Collapsed by default"