# Schema for the configuration files of the Ingredient module.

ingredient.settings:
  type: config_object
  label: 'Ingredient module settings'
  mapping:
    ingredient_name_normalize:
      type: integer
      label: 'Normalize ingredient names to lowercase'

ingredient.units:
  type: config_object
  label: 'Ingredient module units'
  mapping:
    unit_sets:
      type: sequence
      label: 'A list of sets of units of measurement'
      sequence:
        type: ingredient.unit_set

ingredient.unit_set:
  type: mapping
  label: 'An Ingredient set of units'
  mapping:
    name:
      type: label
      label: 'The name of a set of units of measurement'
    units:
      type: sequence
      label: 'The units in a set'
      sequence:
        type: ingredient.unit

ingredient.unit:
  type: mapping
  label: 'An Ingredient unit'
  mapping:
    name:
      type: label
      label: 'A singluar ingredient unit name'
    plural:
      type: label
      label: 'A plural ingredient unit name'
    abbreviation:
      type: label
      label: 'The abbreviation for an ingredient unit name'
    aliases:
      type: sequence
      label: 'A list of alternate names or abbreviations for units'
      sequence:
        type: string
        label: 'An alternate name or abbreviation for a unit'

field.storage_settings.ingredient:
  type: mapping
  label: 'Ingredient field storage settings'
  mapping:
    target_type:
      type: string
      label: 'Type of item to reference'

field.field_settings.ingredient:
  type: mapping
  label: 'Ingredient field settings'
  mapping:
    handler:
      type: string
      label: 'Reference method'
    handler_settings:
      type: entity_reference_selection.[%parent.handler]
      label: 'Entity reference selection settings'
    default_unit:
      type: string
      label: 'The default unit to display in the ingredient widget'
    unit_sets:
      type: sequence
      label: 'A list of enabled unit sets to be displayed by the field widget'
      sequence:
        type: string
        label: 'An enabled unit set to be displayed by the field widget'

field.formatter.settings.ingredient_default:
  type: mapping
  label: 'Ingredient field formatter settings'
  mapping:
    fraction_format:
      type: string
      label: 'Fractions display string'
    unit_display:
      type: integer
      label: 'Ingredient unit display'
    link:
      type: boolean
      label: 'Link name to the referenced ingredient'
