id: recipe713_ingredient_settings
label: Ingredient configuration
migration_tags:
  - Drupal 7
source:
  plugin: variable
  variables:
    - recipe_ingredient_name_normalize
  source_module: recipe
process:
  ingredient_name_normalize: recipe_ingredient_name_normalize
destination:
  plugin: config
  config_name: ingredient.settings
