field.field.node.content_page.field_page_section:
  add:
    settings:
      handler_settings:
        target_bundles:
          d_p_block: d_p_block
        target_bundles_drag_drop:
          d_p_block:
            enabled: true
            weight: 38
