core.entity_view_display.media.d_image.default:
  add:
    content:
      field_media_image:
        third_party_settings:
          lazy:
            lazy_image: '1'
core.entity_view_display.media.d_image.d_banner:
  add:
    content:
      field_media_image:
        third_party_settings:
          lazy:
            lazy_image: '1'
core.entity_view_display.media.d_image.carousel_item:
  add:
    content:
      field_media_image:
        third_party_settings:
          lazy:
            lazy_image: '1'
core.entity_view_display.media.d_image.counter:
  add:
    content:
      field_media_image:
        third_party_settings:
          lazy:
            lazy_image: '1'
core.entity_view_display.media.d_image.d_icon:
  add:
    content:
      field_media_image:
        third_party_settings:
          lazy:
            lazy_image: '1'
core.entity_view_display.media.d_image.d_tiles_gallery_fullscreen:
  add:
    content:
      field_media_image:
        third_party_settings:
          lazy:
            lazy_image: '1'
core.entity_view_display.media.d_image.full:
  add:
    content:
      field_media_image:
        third_party_settings:
          lazy:
            lazy_image: '1'
core.entity_view_display.media.d_image.gallery_item:
  add:
    content:
      field_media_image:
        third_party_settings:
          lazy:
            lazy_image: '1'
