field.field.paragraph.d_p_side_by_side.field_d_p_sbs_items:
  add:
    settings:
      handler_settings:
        target_bundles:
          d_p_media: d_p_media
        target_bundles_drag_drop:
          d_p_media:
            enabled: true
            weight: 50
