# Schema for the views plugins of the Recipe module.

views.display.recipe:
  type: views_display_path
  label: 'Recipe display options'
  mapping:
    displays:
      type: sequence
      label: 'The format link will be available only to the selected displays.'
      sequence:
        type: string
        label: 'Display'

views.style.recipe_plain_text:
  type: views_style
  label: RecipeML
  mapping:
    hide_empty:
      type: boolean
      label: 'Hide empty'
    wordwrap_width:
      type: integer
      label: 'Wordwrap width'
    row_separator:
      type: string
      label: 'Row separator'

views.style.recipeml:
  type: views_style
  label: RecipeML
  mapping:
    title_field:
      type:  string
      label: 'Title field'
    version_field:
      type:  string
      label: 'Version field'
    source_field:
      type:  string
      label: 'Source field'
    time_fields:
      type: sequence
      label: 'Preptime fields'
      sequence:
        type: string
        label: 'Fields'
    yield_qty_field:
      type:  string
      label: 'Yield quantity field'
    yield_unit_field:
      type:  string
      label: 'Yield unit field'
    description_field:
      type:  string
      label: 'Description field'
    ingredients_field:
      type:  string
      label: 'Ingredients field'
    directions_field:
      type:  string
      label: 'Directions field'
