# Schema for the configuration files of the Recipe module.

node.type.*.third_party.recipe:
  type: mapping
  label: 'Recipe node type third-party settings'
  mapping:
    total_time_label:
      type: label
      label: 'The label for the Total time pseudo-field.'
    total_time_label_display:
      type: string
      label: 'The display setting for the Total time pseudo-field label.'
    yield_label:
      type: label
      label: 'The label for the Yield pseudo-field.'
    yield_label_display:
      type: string
      label: 'The display setting for the Yield pseudo-field label.'

field.field.*.*.*.third_party.recipe:
  type: mapping
  label: 'Recipe field settings'
  mapping:
    total_time:
      type: boolean
      label: 'Whether to add this integer field to the Recipe total time.'

field.formatter.settings.ingredient_recipeml:
  type: mapping
  label: 'Ingredient field RecipeML formatter settings'
  mapping:
    fraction_format:
      type: string
      label: 'Fractions display string'
    unit_display:
      type: integer
      label: 'Ingredient unit display'
