field.formatter.settings.number_formatter:
  type: mapping
  label: 'Number Formatter style'
  mapping:
    style:
      type: integer
      label: 'Style'
    currency:
      type: string
      label: 'Currency'
    lang_select:
      type: string
      label: 'Language'
