user_attendance.user_attendance_type.*:
  type: config_entity
  label: 'User attendance type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    validation_type:
      type: string
      label: 'Validation type'
    duplicate_protection:
      type: int
      label: 'Duplicate protection'
    uuid:
      type: string
