field.widget.settings.ordered_list:
  type: mapping
  label: 'Ordered list widget settings'
  mapping:
    open:
      type: boolean
      label: 'Display element open by default'
    labels:
      type: mapping
      label: 'Labels'
      mapping:
        items_available:
          type: label
          label: 'Available items label'
        items_selected:
          type: label
          label: 'Selected items label'
        control_select:
          type: label
          label: 'Select control label'
        control_deselect:
          type: label
          label: 'Deselect control label'
        control_moveup:
          type: label
          label: 'Move up control label'
        control_movedown:
          type: label
          label: 'Move down control label'
